name: Run setup-node
description: Set up nodejs environment for GitHub Actions

runs:
  using: composite
  steps:
    - name: Cache node_modules
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - name: Install npm
      run: npm ci
