baseURL = "http://example.com"
title = "takeokunn's blog"
theme = "hugo-take-theme"

[params]
author = 'takeokunn'
description = "takeokunn's blog"
image = "ogp.png"
gtag = "UA-135483596-1"
twitter = "takeokunn"
github = "takeokunn"
