baseURL = "http://takeokunn.org/"
title = "takeokunn's blog"
theme = "hugo-take-theme"
canonifyurls = true

[params]
author = 'takeokunn'
description = "takeokunn's blog"
ogpImage = "ogp.png"
icon = "icon.png"
gtag = "UA-135483596-1"
twitter = "takeokunn"
github = "takeokunn"

[taxonomies]
tag = "tags"
