baseURL = "https://takeokunn.org/"
title = "takeokunn's blog"
theme = "hugo-take-theme"
canonifyurls = true
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  author = 'takeokunn'
  description = "takeokunn's blog"
  ogpImage = "https://takeokunn.org/ogp.png"
  icon = "icon.png"
  gtag = "UA-135483596-1"
  twitter = "takeokunn"
  github = "takeokunn"

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
