title = "takeokunn's blog"
baseURL = 'https://www.takeokunn.org/'

defaultContentLanguage = "ja-jp"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]
theme = "hugo-take-theme"

[params]
DateForm = "2006.1.2"

[services]
[services.googleAnalytics]
id = 'UA-135483596-1'

[markup]
[markup.highlight]
noClasses = true

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

[taxonomies]
tag = "tags"

[Languages.ja-jp]
languageName = "Japanese"
languageCode = "ja-jp"
contentDir = "content/"

[Languages.ja-jp.params]
mainSections = ['posts']
dateFormat = "2 May 2023"

[outputFormats]
[outputFormats.TXT]
mediaType = "text/plain"
baseName = "llms"
isPlainText = true

[outputs]
home = ["HTML", "TXT"]
