:PROPERTIES:
:ID:       8519D7FF-9185-4CA5-86D0-2B55710FD38E
:END:
#+TITLE: 2025年2月名古屋旅行
#+AUTHOR: takeokunn
#+DESCRIPTION: description
#+DATE: 2025-02-24T14:07:46+0900
#+HUGO_BASE_DIR: ../../
#+HUGO_CATEGORIES: diary
#+HUGO_SECTION: posts/diary
#+HUGO_TAGS: diary
#+HUGO_DRAFT: false
#+STARTUP: content
#+STARTUP: fold
* Introduction
2025/2/21から2025/2/24までの名古屋旅行についての振り返りです。

名古屋上陸ははじめてでしたが、非常に楽しい旅行になりました。思い出したらまた追記するかもしれません。
* 注意
このブログはあくまで個人的な旅行記であり、「たけてぃのことを知っている or 物好きな人」向けの記事です。
帰りの高速バスの中で暇なので書いているくらいの温度感の記事なので真に受けないでください。

社会人として外面の良い活動はZennに後日纏めますので少々お待ちください。
* スケジュール
スケジュールはざっくり以下です。
今回の旅行も常に何かをしていたなという感覚があります。

| 開始日   | 開始時間 | 終了時間 | 項目                                  |
|----------+---------+---------+---------------------------------------|
| 2/21(金) |   23:00 |   07:00 | 夜行バス 東京駅 → 名古屋駅               |
| 2/22(土) |    9:30 |   19:00 | phpcon名古屋                          |
|          |   19:00 |   21:00 | 懇親会                                |
|          |   21:00 |   23:30 | 2次会                                 |
|          |   23:30 |   24:00 | 湯〜とぴあ宝 移動                       |
| 2/23(日) |   10:00 |   11:30 | 名古屋駅にてモーニング                   |
|          |   11:30 |   13:00 | 喫茶マウンテン with tadsan, あかつかさん |
|          |   13:30 |   16:30 | 東山動物園                             |
|          |   17:00 |   19:00 | ひつまぶし in 栄 with tadsan           |
|          |   19:00 |   21:00 | 栄散策                                |
|          |   21:00 |   22:00 | 名古屋駅周辺散策 +  湯〜とぴあ宝 移動     |
| 2/24(月) |    9:30 |   11:30 | 名古屋駅にてモーニングと定食を食べる       |
|          |   11:30 |   12:00 | お土産買ってバス停に移動                 |
|          |   12:00 |   18:00 | 高速バス  名古屋駅 → 東京駅              |

* ドメイン用語
普段なにげなく使っているが、よくよく考えたら初見の人から見たら意味がわからない単語、それがドメイン用語なのです。

vim-jp slackだと「テキストエディタに目覚める」や「yasunori」など入門するのがむずかしい内容が多々あります。
俺ときんじょうさんとの間のドメイン用語はまだ入門しやすいと思います。

- 鳥貴族関連
  - うぬぼれ
  - 焼き鳥
- エターナルホスピタリティ
  - 鳥貴族の運営会社名
- 刃牙で比喩する
  - e.g. 強者に生まれてツールに頼るのは女々しい
  - e.g. 「まだやるかい」と残業を心配する上司花山薫
- ノブレスオブリージュ
  - 何か仕事を達成した時に使う言葉
- きんじょうさんへ
  - ピーチ姫の「マリオへ」の改変
- 地方カンファレンスまで歩いて行く
  - 「方角」の話をしているので嘘ではないこともある

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">ワシが一番悲しんどるんじゃぁ！！<br><br>地下PHP場戦士の最強を誰よりも信じたのはワシじゃ！貴様等にこのワシの無念がわかるか！</p>&mdash; 今日も誰かのにちようび(おいしい鮭親子丼) (@o0h_) <a href="https://twitter.com/o0h_/status/1832662771756101891?ref_src=twsrc%5Etfw">September 8, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

また、僕だけが言ってる単語も多々あります。

- 無職の休日倶楽部
  - 元同僚(A氏)が仕事辞めた後に「無職の休日倶楽部」とツイートしまくってたのに感銘を受けて使っている
  - 実際は残念ながら仕事をしている
  - 以前「無職には休日という概念がないよ」とTwitterでマジレスをされたことがある
- 昼間はOL
  - Twitter(自称X)のプロフィール
  - 昔ネカマやってた時のプロフィールをそのまま使っている
- 具体か抽象か(それhowなんよな)
  - そーだいさんの発表を揶揄する意図は一切ない

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">焼き鳥は</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893457761330962642?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export
* 各イベントの感想
** 高速バス
夜行バスに乗るのは人生初でした。
「3列シートにしておけ」という初先輩方の助言により3列シートにしたのですが、普段よりは快適でした。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">旅の始まり <a href="https://t.co/QVfXWs01u9">pic.twitter.com/QVfXWs01u9</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1892934994475278603?ref_src=twsrc%5Etfw">February 21, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">夜行バス初めてだけどめっちゃいいな</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1892939789558558812?ref_src=twsrc%5Etfw">February 21, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

登壇スライドを作っていたのですが、目の前の客が無呼吸といびきと過呼吸を繰り返してて猛烈に心配になりました。
こういうのって自分じゃ気がつけないものなので強く生きてほしいです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">目の前の客の無呼吸症候群が気になって起きた</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1892992608944738745?ref_src=twsrc%5Etfw">February 21, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

深夜のサービスエリアはエモいです。
バスの運ちゃんが疲れた顔しながら煙草吸ってるのとか非常にエモいですね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">深夜のサービスエリアエモいな <a href="https://t.co/27XIXXxnt6">pic.twitter.com/27XIXXxnt6</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893004246595051855?ref_src=twsrc%5Etfw">February 21, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export


帰りは昼間の高速バスで帰りました。
天気が良いのもあり富士山が映えますね。
たまたま一番後ろの席になったのですが、席を倒し放題なので爆睡しました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">あかりサービスエリア大好き <a href="https://t.co/XrLEQ4mHWL">pic.twitter.com/XrLEQ4mHWL</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893917988656464061?ref_src=twsrc%5Etfw">February 24, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export
** phpcon名古屋

こちらは別途Zennに「社会人として適切な文章」で書きますので少々お待ちを。

*** プロポーザル
phpcon東京でプロポーザルが全落ちしたことが確定した時、「プロポーザルを名古屋にそのままコピペで提出すればいいよ」というツイートが流れてきました。
なので、何も考えずにそのツイートを見た3分以内にコピペで提出をしました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">⋱📣トーク募集中です📣⋰<a href="https://twitter.com/hashtag/phpcon?src=hash&amp;ref_src=twsrc%5Etfw">#phpcon</a> のプロポーザル採択結果が発表されましたね！残念ながら見送りとなってしまった方、そのネタ <a href="https://twitter.com/hashtag/phpcon_nagoya?src=hash&amp;ref_src=twsrc%5Etfw">#phpcon_nagoya</a> にぶつけてみませんか？！<br><br>ここからコピーして…<a href="https://t.co/OpwQfAROqx">https://t.co/OpwQfAROqx</a><br><br>ここでペースト！簡単！<a href="https://t.co/9z3ckumBD0">https://t.co/9z3ckumBD0</a><br><br>ご応募お待ちしてます！🍤</p>&mdash; PHPカンファレンス名古屋 (@phpcon_nagoya) <a href="https://twitter.com/phpcon_nagoya/status/1840209891774083318?ref_src=twsrc%5Etfw">September 29, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

基本的に練馬から遠い地方phpconはプロポーザルが通ったら旅行ついでに行く、くらいの温度感で毎回出しています。
ありがたいことなのですが、なんかよくわからない間にプロポーザルが通りました。
*** 登壇準備
登壇駆動ではなくそもそも仕事でやっていた内容なので、話したいことは夜行バスより前に箇条書きで書き出していました。
直近とにかく忙しくててんやわんやしていたのでスライド作成まで手を出せていませんでした。

結局スライドは夜行バスの中と開会までの間に名古屋駅のカフェで40枚作りきりました。
夜行バスはかなり揺れるので三半規管に自信ニキしか真似できなさそうです。
スピーカーノートを作りこんでおくと、実際の登壇で言い回しに困らなくなって良いというのを経験上知っているので、ひたすら他の人の登壇を聞きながら頭の中でメモをして練習をしていました。
スピーカーノートを作りこむのオススメですよ。

結局素振りをせずに本番を向かえたのでとにかく余裕がなかったです。
僕みたいな計画性のない奴は絶対に登壇駆動で何かをするべきではないです。

[[id:0D13FCEA-F8EC-4729-B700-9A88FD1D5EB9][NixでTypstをBuildしGitHub Pagesでホスティングする]] にある通り、今回はtypstでスライドを生成しようかなと思ったのですが、夜行バスのネット環境が貧弱なこと、typstでスライドを作るのが初めてなこと、時間がないので失敗できないことを加味してGoogle Slideで作りました。
*** 本番
Google Slideのスピーカーモードで開始ボタンを押し忘れて、今何分経過したのか分からない状態でしたが、そんな中本番はぴったり15分で話せてよかったです。
観客の反応も良かったし、ちょこちょこウケも取れて大満足でした。睡眠不足の深夜テンションでもなんとかなってほっとしました。

タイトルコールは平野綾さんでしたが、たけてぃと名前を呼ばれるなんてもうニッコニコですよ。オタク君としてはもう最高。
これだけでも名古屋に来てよかったなと思います。

個人的にはらきすたのこなたっぽくも呼ばれたかったので、来年も平野綾さんを呼んでほしいですね。

強欲でしょうか? いいえ誰でも。

今回はまきちゃんの登壇が裏番組でした。
げんえいさんは「たけてぃの発表はまー資料読めばいいからなー」といってまきちゃんの方に行ったらしく、ザブングル加藤みたいな顔になりました。
とはいえ、げんえいさんの立場になったら僕もそうしてたので何も言えませんでした。
*** 懇親会
懇親会は立食パーティ形式で料理が美味しかったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr"><a href="https://twitter.com/hashtag/phpcon_nagoya?src=hash&amp;ref_src=twsrc%5Etfw">#phpcon_nagoya</a> 懇親会！ <a href="https://t.co/BXr12T1kx0">pic.twitter.com/BXr12T1kx0</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893238756808757675?ref_src=twsrc%5Etfw">February 22, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

[[https://zenn.dev/takeokunn/articles/20250211225710][Software Design3月号]] を読みましたと言ってくれた方が多くて、こういう外部へのアウトプットをするのは中々良いものだなと思いました。

毎回固定の人と話しがちなのなんとかしたいなと思いつつ、新規の人にどう話しかけて良いのか毎回悩みますね。
本質的には僕個人の会話デッキの少なさが原因なので、交流のうまい人を参考にしながら上達していきたいものです。

今回は普段よりはかなり話せた方で自分としては健闘できました。
登壇すると話しかけられるというのは真なので、みんなどんどんプロポーザル出そうね。
*** 2次会
2次会は名古屋の魚や土手煮など名古屋グルメが出てきました。

特に02さんと初対面の方(名前を存じ上げない)と3人で盛り上がりました。
あまりにも初対面の方が言ってることが共感しすぎて「そうそうそう」と言い続けるbotと化していました。
やはり俺達はちゃんと打席に立って全打席でホームランを打つ覚悟でいなくてはいけないし、技術のトレンドをちゃんと追いかけていきたいし、Howを極めていきたいという気持ちになりました。

今年のphpcon東京に来るっぽいのでおっさんとまた飲みに行きたいです。是非誘ってください。

流石に睡眠不足なのもあって3次会には参加しませんでした。
** 湯〜とぴあ宝(宿)
全国30人のたけてぃゴミ宿レポートを楽しみにしている皆さんには悲報です。
湯〜とぴあ宝はめちゃめちゃ良かったです。

当初はドヤ街にある一泊1600円の宿に泊まる予定だったのですが、直前に予約しようとしたのもあって取れませんでした。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">「独房のようだがくろろげる空間」<a href="https://t.co/ap2AZNp6B6">https://t.co/ap2AZNp6B6</a> <a href="https://t.co/JuvRfZXaml">pic.twitter.com/JuvRfZXaml</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1863991015537053842?ref_src=twsrc%5Etfw">December 3, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

旅行ソムリエのぷぷさんに「湯〜とぴあ宝いいよ」と言われて直前の火曜日に急いでバスと一緒に予約しました。

https://www.yu-t.com/

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">最高だったありがとう <a href="https://t.co/B0uJUPY10J">pic.twitter.com/B0uJUPY10J</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893820559063998596?ref_src=twsrc%5Etfw">February 24, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

内観は非常に綺麗でお風呂も沢山あり漫画コーナーや自販機や子供向けゲームセンターなども充実している非常に良い健康ランドでした。
笠寺駅は名古屋駅から30分程度で着くのでそこも魅力です。

プレミアムプランは宿泊プランで、カーテンで区切られた準個室のような空間でした。
2人分がギリ横になれるかくらいの広さですが、温度湿度も管理されており、快適に睡眠できました。
値段は6500円で僕が普段泊まる宿の2倍くらいの料金です。

サウナは4種類、水風呂は15℃とちょうど良く、椅子やベッドも充実しておりサウナーとしては大満足でした。

- フィンランド風サウナ
- 竹炭ドライサウナ
- ミストサウナ
- 冷房室

** 喫茶マウンテン
[[https://ja.wikipedia.org/wiki/%E5%96%AB%E8%8C%B6%E3%83%9E%E3%82%A6%E3%83%B3%E3%83%86%E3%83%B3][噂の喫茶マウンテン]]にtadsanとあかつかさんと行ってきました。

名古屋市内から1時間以内につく距離でそこそこ遠かったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">PHPerといく喫茶マウンテン登頂ツアーが開催されそうなので興味ある方いたら</p>&mdash; にゃんだーすわん (@tadsan) <a href="https://twitter.com/tadsan/status/1893476384552689799?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

店内はレトロな雰囲気で非常に趣があって良かったです。
メニューも「いかすみ」や「妹のラムネ」など謎なものが多かったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">ドリンクにイカスミがある... <a href="https://t.co/mLwXnVwdwq">pic.twitter.com/mLwXnVwdwq</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893497394148561172?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

スイーツパスタを食べはじることを「登山」、食べれないことを「遭難」と言うらしいのですが、秒速で遭難しました。
こんなに美味しくないものを食べたのは久し振りでした。

パスタの温かさで生クリームが微妙に溶けている状態も美味しくなさすぎるし想像の5000倍不味かったです。
一旦口に入れた時に「これはやばい、はやく飲み込め」と脳は命令しているのに「これを受け入れる訳にはいかない」と胃が拒絶してる時間が長くあり、結果口の中に美味しくないものが残り続けて地獄でした。

結果吐くよりはマシかということで半分以上残して遭難しました。すみません。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br>喫茶マウンテン登山開始 <a href="https://t.co/DCnrDYazIQ">pic.twitter.com/DCnrDYazIQ</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893503926667743278?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

一緒に行った2人はなんとか完食していて、自分が食に対して保守的なんだなとあらためて思いました。
tadsanに関しては黙々と食べてて怖かったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">すまん、tadsanが速攻で完食してて絶望してる</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893507563548704972?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">あかつかさんは「クレープと脳を錯覚させてなんとか食った」みたいだが、tadsanは黙々と食ってたので今後のtadsanとの付き合い方を考えなければならない</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893514707614490916?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

個人的には最悪な気分だったのですが、飲み会のスベらないネタが手に入ってそういう意味では美味いですね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">後悔はいつだって後からしか出来ない <a href="https://t.co/hpn1OSGAbf">https://t.co/hpn1OSGAbf</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893518200966455737?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

スイーツパスタがやばいだけで普通のメニューは美味しそうだったのでレトロ喫茶が好きな人は是非普通のメニューを頼むといいです。

** 東山動物園

喫茶マウンテンの近くに東山動物園があったので折角だしということで行きました。

東山動物園は動物の種類がとにかく多く、兎に角広いです。
13:30頃に着いて閉園が16:30頃まで3時間くらいひたすら歩きまわっていました。
理想は奥にある植物園まで行きたかったのですが流石に時間がなかったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br>東山動物園楽しい <a href="https://t.co/qRR3pajNtq">pic.twitter.com/qRR3pajNtq</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893551107860987919?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">追加 <a href="https://t.co/NG7yHVgUMV">pic.twitter.com/NG7yHVgUMV</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893576248481423512?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

僕はそういう星の元に生まれてきたのかこういうオモシロイベントが起こるんですよね。なんでなんですかね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">夜行性動物コーナーでナマケモノが木の上を器用に動いてたんだけど、隣のカップルが「SASUKE出れんじゃん」って言ってて草<br><br>出れるわけないだろ</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893532874172780929?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">今気がついたけど、アシカを撮ってる奥でカップルがピースしてたw <a href="https://t.co/7fHksIpSi1">pic.twitter.com/7fHksIpSi1</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1894208905418608689?ref_src=twsrc%5Etfw">February 25, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

** 名古屋駅/栄駅 周辺散策

知らない街についた時は一通り練り歩いて街の形を把握するのが好きなのですが、名古屋駅も栄駅もとにかく広くて長時間歩く必要がありました。
そもそも愛知のこと知らなさすぎて栄と名古屋の位置関係を知らなかったのですが、数駅違いでめちゃくちゃ近いんですね。

愛知県民的には名古屋駅の方が都会だと思っているらしいですね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">ちなみに愛知県民は、名古屋が一番都会だと思ってるよ笑</p>&mdash; kenji sakai (@saka0ken) <a href="https://twitter.com/saka0ken/status/1893622261594083769?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

夜の名古屋駅は雰囲気ありますね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">雰囲気ある <a href="https://t.co/gjpGPPZOXu">pic.twitter.com/gjpGPPZOXu</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893230324387049691?ref_src=twsrc%5Etfw">February 22, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

栄のテレビ塔前がまんま札幌でデジャブ感を感じてました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">テレビ塔が見える公園… 名古屋は札幌市だったんだ <a href="https://twitter.com/hashtag/madanagoyaniiruphper?src=hash&amp;ref_src=twsrc%5Etfw">#madanagoyaniiruphper</a> <a href="https://t.co/Xg0wh8PDXA">pic.twitter.com/Xg0wh8PDXA</a></p>&mdash; にゃんだーすわん (@tadsan) <a href="https://twitter.com/tadsan/status/1893523878594650115?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

夜の栄でいつものごとく不動産営業にからまれました。
流石天下のTOYOTA様のお膝元、自動車関係かどうかというので条件分岐が走るんですね。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">不動産営業のおにーちゃんから絡まれて25歳と嘘の年齢を伝えてしまったんだけど、まさかの25歳で嘘がバレるところだった</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893606321053905341?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">「お仕事は何されてるんですか？」<br>「東京でWebサイト作ったりですね」<br>「自動車関係ですか？」<br><br>なわけねぇだろ</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893607434528412064?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

営業のおにーちゃんが不吉なことを言っててひやっとしました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">「いやー僕も前職でサイト弄ってたんですが全部データ吹っ飛ばして会社に損害出しちゃったんですよねー」って言っててどう反応して良いのか分からなかった</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893610375699914834?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

ちなみに前回絡まれたのは福岡でした。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">不動産勧誘「おにいさんちょっといいですか?」<br>俺「なんすか?」<br>不「正社員で年収300万以上だったりします?」<br>俺「俺フリーターすけど...(嘘」<br>不「あーーーやっぱりかーーーーすんません大丈夫っす」<br><br>何が「やっぱり」だよふざけんなって福岡初日キレてた</p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1673665483114004484?ref_src=twsrc%5Etfw">June 27, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export
* 名古屋グルメ
** 2/22(土)

夜行バスから降りで一番最初にきしめんを食べました。
朝一に飲むビールは最高で体の細胞一つ一つに染み渡りました。

[[https://dic.nicovideo.jp/a/%E3%81%8D%E3%81%97%E3%82%81%E3%82%93][きしめええええええええええええええええええええええええええええええええん]] なんて今時知ってる人は何人いるんでしょうかね?
元のゲームをやってみたいと思い早n年ですが、DirectXのバージョン的にも多分もう動かないでしょう。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">だきしめーーーーーん <a href="https://t.co/m6dlFtChY0">pic.twitter.com/m6dlFtChY0</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893075158811975681?ref_src=twsrc%5Etfw">February 21, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

昼はアンチボッチランチということで、phperの皆さんとエビフライを食べました。
エビフライが名古屋で有名ということは知らなかったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">美味かった <a href="https://t.co/gvsFy9T2GJ">pic.twitter.com/gvsFy9T2GJ</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893157440579084408?ref_src=twsrc%5Etfw">February 22, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

写真はないですが、懇親会と二次会では土手焼きと手羽先と海鮮を食べました。

** 2/23(日)

朝はモーニングを食べました。
これが噂の小倉あんかーと思いながらクロワッサンに塗って食べながら優雅な朝を迎えました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br>名古屋名物モーニング <a href="https://t.co/nusWNAXjJ2">pic.twitter.com/nusWNAXjJ2</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893475226073117121?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

昼は東山動物園のスカイタワーの上で地元の白身魚を使ったアクアパッツァを食べました。
もうちょっと白身魚に塩ふった方が味の境界が出て美味しくなりそうだなと思いつつ美味しかったので大満足です。
直前に食べた喫茶モンブランのダメージを緩和できました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">展望台のレストランでアクアパッツァ食べた美味しかった<br><br>白身魚にもう少し塩振って味に輪郭を出した方がもっと美味しくなりそうだなと思った <a href="https://t.co/UaIFolz8j3">pic.twitter.com/UaIFolz8j3</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893551519229976921?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

夜はtadsanと栄でひつまぶしを食べました。最高に美味しかったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">ワサビすってひつまぶしまってる <a href="https://t.co/cU0mxcoXuP">pic.twitter.com/cU0mxcoXuP</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893577273762291987?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">わくわく <a href="https://t.co/nB8KYYnBYO">pic.twitter.com/nB8KYYnBYO</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893577907102233041?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br>ひつまぶし！ <a href="https://t.co/KU1srWVJQe">pic.twitter.com/KU1srWVJQe</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893578832063709374?ref_src=twsrc%5Etfw">February 23, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

** 2/24(月)
昨日に引続きモーニングを食べました。
今回はプレーンなモーニングを楽しもうと、トーストと茹で卵のみのセットにしました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br><br>ラストモーニング <a href="https://t.co/FaKLl44pSv">pic.twitter.com/FaKLl44pSv</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893838050750317032?ref_src=twsrc%5Etfw">February 24, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

よく考えたら手羽先も土手煮も味噌カツも飲み会のつまみ程度にしか食べれてなく、このまま東京に帰るのは勿体なさすぎるということで、モーニングの直後に名古屋ごちそう定食を食べました。
味噌カツもっと食べたかったです。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">無職の休日倶楽部<br><br>今日もだれかのにちようび <br>美味しい名古屋ごちそう定食 <a href="https://t.co/NOAykBqOLe">pic.twitter.com/NOAykBqOLe</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1893846462611521817?ref_src=twsrc%5Etfw">February 24, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export
* 終わりに
当初の名古屋の期待値は死ぬほど低かったんですが、こんなに名古屋旅行楽しいとは思いませんでした。

かなり名古屋観光できたなと思いつつ、結局名古屋城とすがきやに行けなかったのが心残りです。
名古屋は練馬から遠いけどまた行きたいですね。

名古屋民はもっと自信を持って名古屋を語ってください。
「名古屋の魅力? [[https://dic.pixiv.net/a/%E3%81%AA%E3%81%84%E3%82%93%E3%81%A0%E3%81%AA%E3%80%81%E3%81%9D%E3%82%8C%E3%81%8C][ないんだなそれが]]」と言うのは栃木だから許されるのです。
* 次遠征する時の自分へ

まずはこちらの「次遠征する時の自分へ」を読みましょう。

- [[id:0227D66A-A96F-420C-8AC6-19EB63C3230E][PHPカンファレンス北海道2024に参加してきました]]
- [[id:F59F81F7-C0AA-4253-9844-4F2B7BB4AEA5][phpカンファレンス福岡2023に参加してきました]]

今回は雪が降っていた時間帯もあったが、福岡と比べて以下のdiffのみで十分でした。

- パーカー追加
- クロックス → 靴と靴下に変更

どちらにせよカバン一つで十分なことには変わりはないし、それ以上を持つのは持ちすぎなので反省してください。

湯〜とぴあ宝は館内着があったから、念の為持っていってた寝間着の半ズボンは不要でした。

高速バスを乗るならアイマスクを持っていくのもあり。
