:PROPERTIES:
:ID:       EEB6FCD7-1F0A-46FB-8456-4A3DD7175313
:mtime:    20231217120109
:ctime:    20221215022943
:END:
#+TITLE: エンジニア採用面接で考えていること
#+AUTHOR: takeokunn
#+DESCRIPTION: エンジニア採用面接で考えていること
#+DATE: 2020-02-02T09:00:00+09:00
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: posts/permanent
#+HUGO_CATEGORIES: permanent
#+HUGO_TAGS: recruit
#+HUGO_DRAFT: false
#+STARTUP: content
#+STARTUP: nohideblocks

これはポエムです。

個人的意見だし、エンジニアの採用面接専門で雇われているわけじゃないので詳しいことやベストプラクティスはわからないです。会社の方針と違う部分もあるし。

2020年2月時点でカジュアル面接/1次面接のときに僕がやっていることについて書いていく。

--------------

** 基本方針

大事なのは次の4点な気がしている。

- コミュニケーションはつつがなく取れそうか
- 技術が好きか
- 誠実かどうか
- 現職（前職）について明瞭に説明できるかどうか

これらを知るためにいろいろな質問をしていく。

ぶっちゃけ趣味なり仕事なりで作っているものを楽しそうに話してもらえるのが一番。

** やること
*** 下準備

- 人ことの方からもらった事前情報を読み込む
- SNS（GitHub/Twitter/YouTube/note/instagram/facebook/wantedly/connpass等） を探す
- GitHubに公開しているコードを読む
- Qiitaや技術ブログを読む

GitHubや技術記事を公開していないと事前情報がまったくなく判断しづらい。

Fish Shellに次のようなfunctionを作って一気にrepoをcloneできるようにしている。

#+begin_src fish
  function ghq_all
      curl "https://api.github.com/users/"(echo $argv)"/repos" | jq -r ".[].clone_url" | xargs -L1 ghq get
  end
#+end_src

技術ブログやサイトをホスティングしている際は、whoisを読んだり、digったり、DOMを読んだりNetworkを読んでどのように配信しているのかを見る。
WordPressだったら ~/wp-admin~ ~/readme.html~ がたたけるかどうかなど、セキュリティ意識できているかも見る。

*** 当日面接

自社説明はテンプレで話すが、それ以外で話す内容は以下。

- 現職（前職）どんな仕事をしているのか
- 好きな、得意な技術は何か
- 直近楽しかった開発は何か、どうやったのか
- 今後どのような風になりたいのか、それに向けてどのような努力をしているのか

事前情報を元に↑の内容を話す。

#+begin_quote
- 現職(前職)どんな仕事をしているのか
#+end_quote

業務のどの部分を担当していて、そこで使われている技術は何か、どのような工夫をしているのかなどを明瞭に話せるかどうかを知りたい。

普通に開発しているだけよりも、[[id:97B78BDA-8DFA-4184-97C4-6C277DE1B539][開発体験向上について考えてること]] を行っている方がよい。

[[https://nazo.hatenablog.com/entry/yarikiru][職業Webエンジニアにおける「実績」と「やりきる力」]]によいこと書いてある。定期的に読み直している。

#+begin_quote
- 好きな(得意)技術は何か
#+end_quote

「Rubyに自信がある」と書いてあったら、それは「Rubyの言語自体に自身がある」のか「RailsのFW自体に自身がある」のか、「Railsを使うの自信がある」のかを正確に知りたい。

用語を正確に使えているのかどうかと、それに対しての知識がどのくらい深いかどうかと、そのことに対してどのくらい自覚があるのかを見る。

#+begin_quote
- 直近楽しかった開発は何か、どうやったのか
#+end_quote

技術が純粋に好きか、楽しく開発しているということは技術的チャレンジをしている可能性が高いのでなるべく聞くようにしている。

#+begin_quote
- 今後どういう風になりたいのか、それに向けてどういう努力をしているのか
#+end_quote

「勉強中です」っていうのは情報量0ですので、「何の勉強をしていて、どのようなロードマップがあって、今どこなのか」みたいな話をしてもらえると理解しやすい。

*** 面接振り返り

- 話したことを振り返る
- 社内の面接評価基準と照らし合わせて評価を作成する
- まとめて人ことの方に伝える

一緒に働いて楽しそうか、活躍できそうかどうかなど社内の面接指標に合わせて評価をする。

** まとめ

1回の面接に結構エネルギーを使うけど、いろんな人いるんだなぁっていうのがわかって結構楽しい。

あと落ちたからといって、必ずしもスキルが足りないとかいうわけでもなく、枠がなかっただけの場合もあるのでいちいち落ち込む必要ないんだなぁってのがわかってよかったです。
