:PROPERTIES:
:ID:       4AC3FB19-86D8-42E6-9386-73EBEAA24C7C
:END:
#+TITLE: 2024年 全体振り返り
#+AUTHOR: takeokunn
#+DESCRIPTION: description
#+DATE: 2025-01-05T13:00:00+0900
#+HUGO_BASE_DIR: ../../
#+HUGO_CATEGORIES: permanent
#+HUGO_SECTION: posts/permanent
#+HUGO_TAGS: permanent
#+HUGO_DRAFT: true
#+STARTUP: content
#+STARTUP: fold
* Introduction

2024年振り返りの振り返り記事です。
立てた目標に対してどうだったか、2025年はどうするべきかを書いておきます。

* 年始に立てた目標

プログラミングのほぼすべての問題は「Aという問題に対してBというツールを使ってCをする」の連続だということに気がつきました。
「日報を書く時はorg-modeのテンプレートを使って記述する」や「日本語を書く時はskkを使って入力する」など、それぞれの問題は細分化をするとほぼすべてこの形式になります。

プログラマーは得てしてAという問題を解決したいだけなのに、「BよりB'の方が良いのではないか」と検証をし始めていっこうにCできないものです。
とはいえツールの選定は生産性に直結するので重要でありそこの塩梅が非常に難しいです。

そこで2024年は5年後も使えるであろうツールの選定を十分にすることにしました。
自分が持っているすべての「Aという問題に対してBというツールを使ってCをする」をテンプレ化し、再利用性と再現性を高くするのを目標にしました。

いろいろな話を見聞きした結果、以下の3つを頑張るのが良さそうだということで目標に据えました。

- 文芸的プログラミング（org-mode）
- Nix
- LLM/Local LLM

* 目標に対しての振り返り

| 目標               | 自己評価 |
|--------------------+---------|
| 文芸的プログラミング | ○       |
| Nix                | ◎       |
| LLM/Local LLM      | △       |

2024年はNix元年というくらい、Nixに大量に時間を投資したのは大成功でした。
自分が持っているほぼすべての設定を [[https://github.com/takeokunn/nixos-configuration][takeokunn/nixos-configuration]] とprivate repoに移植しました。
明示的にコードに落とすことによって、自分は今何をどういう設定でどういう用途で使っているのかを明確にできました。

文芸的プログラミングは去年書いた [[id:3BECED15-4350-42B1-98F5-C1D502816F0D][2023年のorg-mode活用と今後の抱負]] から大きな進展はないですが、細やかな改善をたくさん行えた結果、ほぼテンプレ行動でやりたいことを実現できるようになりました。

LLM/Local LLMに関しては、どのくらいの将来性があるのか、やりこむとしたら何をやればよいのか、Local LLMなら何ができるのか等を自分の中で整理するというのが目標でした。
一応自分の中では整理がついたのでそれは良かったのですが、Difyの活用やワークフローに落とし込む所までは間に合わなかったです。

* コミュニティ活動

| 時期 | イベント名                            | 役割         | 登壇スライド                                                                     | 関連                                           |
|------+--------------------------------------+--------------+---------------------------------------------------------------------------------+------------------------------------------------|
| 1月  | [[https://phpcon.hokkaido.jp/][PHPカンファレンス北海道]]                | 参加者       |                                                                                 | [[id:0227D66A-A96F-420C-8AC6-19EB63C3230E][PHPカンファレンス北海道2024に参加してきました]]       |
| 3月  | [[https://phperkaigi.jp/2024/][phperkaigi 2024]]                      | パンフ記事執筆 | [[id:3249F27E-9CE1-4ADC-9B34-607C7DCEC60D][テキストエディタがPHPをシンタックスハイライトする仕組みとモダンテキストエディタ事情について]] |                                                |
| 4月  | [[https://phpcon-odawara.jp/2024/][PHPカンファレンス小田原]]                | 登壇         | [[https://docs.google.com/presentation/d/1436T1dx_0igdNzNCVpGIf0kVA5wOVF4kcVmH9VRJobA/edit#slide=id.p][Laravelに0からPHPStanを導入して継続的に運用する方法]]                                  |                                                |
| 6月  | [[https://phpcon.fukuoka.jp/2024/][PHPカンファレンス福岡]]                  | 登壇         | [[https://docs.google.com/presentation/d/1I5yWPV_hIOaN0FfRQPwyhdQTVFv2uQEK0A08sMHPLiA/edit#slide=id.p][Nixを用いて再現可能なPHP環境を用意する]]                                              |                                                |
| 8月  | [[https://tokyo-emacs.connpass.com/event/321255/][東京Emacs勉強会 サマーフェスティバル2024]] | 主催         |                                                                                 |                                                |
| 10月 | [[https://nix-ja.connpass.com/event/330557/][Nix meetup #1]]                        | 主催、登壇    | [[https://docs.google.com/presentation/d/1So6l6JTNlZkrQDxf99kMFIlPB34TuNdQjpNwgxIBSFo/edit#slide=id.p][nix-shell+org-modeで文芸的プログラミング]]                                           |                                                |
| 11月 | [[https://techbookfest.org/event/tbf17][技術書展17]]                            | 売り子       |                                                                                 | [[https://techbookfest.org/product/f7rPGt7NeeDuqxYdE3Teyc?productVariantID=hATFZbCg6sJxMt5dCXPn4x][めだかのclojure.core学校 conao3]]                 |
| 11月 | [[https://vimconf-2024-ticket.peatix.com/][VimConf 2024]]                         | 個人スポンサー |                                                                                 | [[id:40715FC3-CDA5-4450-BDFB-E185A17980B8][VimConf2024 参加記]]                             |
| 12月 | [[https://isucon.net/archives/58869617.html][ISUCON14]]                             | 競技者       |                                                                                 | [[https://zenn.dev/takeokunn/articles/20241217090756][ISUCON14にチームOL001として参加しました(インフラ編)]] |
| 12月 | [[https://phpcon.php.gr.jp/2024/][PHPカンファレンス東京]]                  | 企業スポンサー |                                                                                 |                                                |

今年は毎月のように何かがあった1年でした。

10月に主催した [[https://tokyo-emacs.connpass.com/event/330572/][東京Emacs勉強会 オクトーバーフェスティバル2024]] と [[https://nix-ja.connpass.com/event/330557/][Nix meetup #1]] は大盛況でオリジナルカクテルを作ったりしました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="qme" dir="ltr"><a href="https://twitter.com/hashtag/nix_ja?src=hash&amp;ref_src=twsrc%5Etfw">#nix_ja</a> <a href="https://t.co/GNbKStEICk">pic.twitter.com/GNbKStEICk</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1850093230521827592?ref_src=twsrc%5Etfw">October 26, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

来年以降のphpcon関連のすでに名古屋、phperkaigi、小田原が決まっています。

また、vim-jpラジオ出演や商業誌の雑誌寄稿が決まっていて来年も忙しくなりそうです。

* イベント

2024年はvim-jpに入り浸ってた一年でした。
emacserのtomoyaさんやconao3と仲良くなれたし、yasunori projectと称してyasunoriの転職活動を全力サポートしました。

カンファレンスついでに旅行たくさんいきました。

| 時期 | 場所      | 目的               |
|------+-----------+--------------------|
| 1月  | 北海道    | PHPCon北海道       |
| 3月  | 秋田      | どっかにビューン旅行 |
| 4月  | 小田原    | PHPCon小田原       |
| 4月  | 大阪、神戸 | 従兄弟の結婚式       |
| 6月  | 福岡、別府 | PHPCon福岡         |
| 8月  | 横須賀    | 地元民の友達と遊ぶ   |

ぷぷさんが主催している [[https://eng-tearoom.connpass.com/][エンジニアティールーム]] はほぼ皆勤賞なくらい参加しました。

#+begin_export html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">良きでした <a href="https://twitter.com/hashtag/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%83%86%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%BC%E3%83%A0?src=hash&amp;ref_src=twsrc%5Etfw">#エンジニアティールーム</a> <a href="https://t.co/jv0wviGEzi">pic.twitter.com/jv0wviGEzi</a></p>&mdash; た҉͜け҉͜て҉͜ぃ҉͜𓁈𓈷 (@takeokunn) <a href="https://twitter.com/takeokunn/status/1662394762576666625?ref_src=twsrc%5Etfw">May 27, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
#+end_export

* 仕事について
** 本業

去年は [[https://zenn.dev/openlogi/articles/bba928c9e07af3][PHPConf2023「保守性の高いアプリケーションを作り続けるための基盤整備について」というテーマで登壇します]] と書いたようにいろいろやりましたが、正直そんなに頑張れてないなという反省があります。
5段階中3くらいの評価でした。

チーム内の人間関係は成功したなーという実感があり、その部分は良かっあです。
職場の9月くらいまで雰囲気が悪かったが今は雰囲気が回復しました。
やはり退職時に暴れ回るのはよくないんだなということを実感しました。

Runbookをとにかく作り、どんどん快適になっていく実感があります。
物流ECドメインに詳しくなって食いっぱぐれないようにしたいですね。

** バイト

土祝日は必ず行くホームになっています。

自分としては好きな技術を使んでるだけなのですが、スタートアップに半身でも置くことはやはり重要なんだなと定期的に思います。

Google App ScriptやWordPressの可能性に気が付けたのは大きかったです。

* 来年の目標

以下の3つをやっていきます。

- 車輪の再発明
- ソフトウェアテスト
- 外部へのリーチを増やす

「車輪の再発明」に関して、コンパイラの自作や以前から作りたかったものを作ります。
アプリケーション実装力を高めるのが目的で、特にLispとPrologに対して時間を投資をしてく予定です。

「ソフトウェアテスト」に関して、生成AIが2024年に一気に伸びて日々のコーディングでも採用できるようになりました。
そうなると動作保証する方法が重要になってきます。
投資していくツールの選定をし、ひたすら使い込み、継続的にテストを回す方法を模索したいです。

「外部へのリーチを増やす」に関して、具体的に以下のようなことをやります。

- ブログやスライドの運用を洗練させる
- EmacsConf 2025開催する
- 勉強会や登壇頻度を増やす
- =技術書展= で本を出したり、雑誌への寄稿をする

* 終わりに
何かを深掘して時間を溶かして調べて良いかの指標として年始に大まかな目標を立て取り組むのは重要だなと感じました。
自分としてはアプリケーションや外部活動に十分に集中するだけの基盤が整ったので、来年はアウトプットに全力を注ぐ1年にしたいです。
