:PROPERTIES:
:ID:       7B19919E-28C6-4A0A-978F-E2D73D06B7EB
:END:
#+TITLE: Emacsユーザーから見たvim-jp
#+AUTHOR: takeokunn
#+DESCRIPTION: description
#+DATE: 2024-01-19T10:37:53+0900
#+HUGO_BASE_DIR: ../../
#+HUGO_CATEGORIES: poem
#+HUGO_SECTION: posts/poem
#+HUGO_TAGS: poem vim-jp
#+HUGO_DRAFT: false
#+STARTUP: content
#+STARTUP: fold
* Introduction

この記事は[[https://vim-jp.org/ekiden/][Vim駅伝]]の2024-01-19の記事です。

前回の記事は[[https://zenn.dev/kawarimidoll][kawarimidoll]]さんの「[[https://zenn.dev/vim_jp/articles/358848a5144b63][俺自身がVimのstatuslineになることだ]]」です。

* この記事を読むにあたっての注意点

- 筆者の主観要素
- 筆者のEmacs愛要素
- 筆者のEmacsコミュニティ活動への努力不足要素
  - 2024年はEmacsイベントを精力的に開催します

* 対象読者

- これからEmacsを始めたい人
- vim-jp slackにまだ参加していない人

* 今北産業

- [[https://blog.tomoya.dev/posts/vim-jp-is-a-paradise-for-engineers/][エンジニアの楽園 vim-jp - 日々、とんは語る。]]を読み [[https://vim-jp.org/docs/chat.html][vim-jpのチャットルームについて]] を参考にvim-jp slackに入る
- =#welcome= で自己紹介をする
- =#hobby-gourmet= で直近の食事をアップロードする

自己紹介テンプレートは以下。

#+begin_example
  はじめまして。
  これからEmacsを学びたくてvim-jp slackに参加しました。
  言語は主に○○を使っていますが、最近は○○を勉強しています。
  よろしくお願いします。
#+end_example
* Vim/Emacsエディタ戦争について
「VimmerとEmacsユーザーは仲が悪い」と[[https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E6%88%A6%E4%BA%89][エディタ戦争]]のようなことを巷ではいわれてますが、実際のところはそんなことありません。
エディタ戦争と言っている人達はどちらのテキストエディタも大して使っていない素人であることが多く、実際のところは少なくとも日本人コミュニティでは一切そんなことありません。

たとえば[[https://github.com/easymotion/vim-easymotion][easymotion/vim-easymotion]]が[[https://github.com/abo-abo/avy][abo-abo/avy]]で再実装されたように、Vim Pluginで有用なものはEmacs Packageに移植されたり、常に互いを高め合うものとして存在しています。（逆もまた然り）

私個人としてはEmacsが世界最強のテキストエディタでありほかのテキストエディタの追随を許さない圧倒的に優れたものだという思想を持っています。
こういう思想を持った私でもVimコミュニティ内で問題なくVimmerと交流できているので、世間が思っている以上にテキストエディタコミュニティは他テキストエディタに寛容です。
* Emacsコミュニティの抱える問題
私がEmacsを始めたのは5年前くらいですが、私の観測範囲内ではコミュニティ活動するEmacsユーザーの数は5年前からほぼ変わらず、悲しいことに新規で入ってくる人はほとんどいません。
つまりEmacsコミュニティは平均年齢が5歳分上がっているのです。

Emacs日本コミュニティに[[https://github.com/emacs-jp/emacs-jp.github.com][emacs-jp slack]]があります。
分からないことがあったらちょっとしたことでも =#question= に気軽に投げてほしいし、 =#today-i-learned= に学んだことを共有してほしいです。
しかし残念ながら投稿の流速が遅く、特に初心者は雑談や質問しつらいという現状があります。

同じくらいの初心者が少ない技術コミュニティでは、質問するのも人間関係を構築するのも難易度がどうしても高くなってしまいます。
ベテラン達も「イマドキEmacsを長い時間苦労してやらずにVSCodeとか使った方がいいんじゃないか?」と思っている人も少なくなく、初心者を増やす活動を中々できていないという側面もあります。

本来なら[[https://gorillavim.connpass.com/][ゴリラ.vim]]のような初心者歓迎イベントを定期開催して、少しでもEmacsへのハードルを下げるべきなのかもしれないなと反省しています。
* vim-jp slackって何？

[[https://blog.tomoya.dev/posts/vim-jp-is-a-paradise-for-engineers/][エンジニアの楽園 vim-jp - 日々、とんは語る。]] に非常に分かりやすくまとまっています。
vim-jpはVimという名前を冠しているにもかかわらず、以下のようなchannelがあり生活全般の会話をできます。（あくまで一例）

- =#hobby-*=
  - =#hobby-gourmet= : 食事全般
  - =#hobby-gadget= : ガジェット全般
- =#life-*=
  - =#life-housekeeping= : 家事全般
  - =#life-healthcare= : 健康全般
- =#event-*=
  - =#event-gorillavim= : ゴリラvim関連
- =#game-*=
  - =#game-minecraft= : マイクラ関連
- =#times-=
  - =#times= : 全員の分報
  - =#times-take= : 私の分報

Emacsユーザーは以下のチャンネルに入っておくことをお勧めします。

- =#tech-emacs=
- =#lang-lisp=
- =#tech-ime=
- Emacsユーザーのtimes
  - =#times-take=
  - =#times-conao3=
  - =#times-tomoya=
  - =#times-ogata=
  - =#times-rocktakey=
  - =#times-kamesuke42=

正直 =#tech-emacs= はEmacs-jpよりも流速があるのでこっちで質問した方が回答が来る可能性が高いです。

vim-jp一番の魅力はテキストエディタを第一線でやっている人とコミュニケーションを取れることです。
たとえば [[https://blog.tomoya.dev/posts/only-those-who-want-to-be-the-wind-should-use-emacs-2020/][風になりたい奴だけがEmacsを使えばいい 2020]] や[[https://gihyo.jp/book/2017/978-4-7741-9235-2][［改訂新版］Emacs実践入門]]の著者の[[https://twitter.com/tomoyaton][tomoya]]氏や、Vimのキラーアプリケーションを次々に作っている暗黒美夢王こと[[https://github.com/Shougo/][Shougo]]氏とも気軽に交流できます。

業界で著名なエンジニアがごろごろいる環境というのはvim-jpくらいじゃないでしょうか。

vim-jpはスタンプによるリアクションも多いところも魅力です。[[https://blog.tomoya.dev/posts/vim-jp-is-a-paradise-for-engineers/#%e5%8f%a4%e3%81%8d%e8%89%af%e3%81%8d%e9%9b%91%e8%ab%87%e6%96%87%e5%8c%96%e3%81%ae%e3%82%a4%e3%83%b3%e3%82%bf%e3%83%bc%e3%83%8d%e3%83%83%e3%83%88][古き良き雑談文化のインターネット]] を感じることができます。
* vim-jpの歩み方

以下の5ステップを行えばあなたも立派なvim-jpの住人といえるでしょう。

** 1. vim-jp slackに参加する

[[https://vim-jp.org/docs/chat.html][vim-jpのチャットルームについて]] を参考にvim-jp slackに参加しましょう。

** 2. #welcome に自己紹介を投げる

vim-jpには =#welcome= という自己紹介チャンネルがあり、自分の興味関心に応じてチャンネルを紹介してくれます。
自己紹介をどう書けば良いか分からない人は以下のテンプレートをお使いください。

#+begin_src markdown
  はじめまして。
  これからEmacsを学びたくてvim-jp slackに参加しました。
  言語は主に○○を使っていますが、最近は○○を勉強しています。
  よろしくお願いします。
#+end_src
** 3. 興味のあるチャンネルに入って雰囲気をつかむ
[[*vim-jp slackって何？][vim-jp slackって何？]] で紹介したチャンネルや自分が興味のあるチャンネルを検索して調べてみてください。
たとえばphpを普段書いているなら =#lang-php= だったり、これからNixを始めたいなという人は =#tech-nix= もあります。

「こういうチャンネルない？」という質問は =#random= に気軽に投げてみてください。
** 4. #hobby-gourmet にご飯の画像を投稿する

はじめて入ったコミュニティに投稿するのはやはりハードルが高いものです。
そういう時は =#hobby-gourmet= に飯の画像を上げたり、 =#hobby-gadget= に最近買ってよかったガジェットの画像を上げてみましょう。

=#times-take= に「この記事を見てvim-jpに参加しました」と投稿してもらえると嬉しいです。

兎に角投稿へのハードルを下げましょう。
** 5. [optional] 自分のtimesを作成する

=#times-<username>= という命名規則なら自由にチャンネルを作成しても良いです。
作成したら =#times= あたりに「 =#times-<username>= を作りました！!」と投稿しましょう。

=#times-<username>= にはちょっとした作業メモや質問まではいかないちょっとした疑問、楽しかったことなどTwitter的な運用をすると良いです。
dotfilesのコミットログを流している人もいます。
* vim-jp最高!!
テキストエディタの話を好きなだけできるコミュニティでvim-jpほど適した場所はありません。
vim-jpの住人はみんなテキストエディタが大好きです。

また、vim-jpは非常に巨大なコミュニティなので必ず自分の興味のあるチャンネルがあるはずです。もしないなら作りましょう。

この記事がvim-jp slack参加の一助になれば幸いです。

Enjoy your vim-jp life!!
