:PROPERTIES:
:ID:       212C336E-3686-4262-9816-19009AC306C0
:mtime:    20231130091715
:ctime:    20231118133259
:END:
#+TITLE: VimConf 2023 Tinyに参加しました
#+DESCRIPTION: description
#+DATE: 2023-11-18
#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: posts/diary
#+HUGO_TAGS: diary
#+HUGO_DRAFT: true
#+STARTUP: content
#+STARTUP: nohideblocks
* Introduction

2023/11/18 (土) 13:00-19:30 JSTに行われたVimConf 2023 Tinyに参加しました。
https://vimconf.org/2023/

VimConfに参加するのは初めてで、普段会えないVimmer交流することができました。

* セッション
** Bram Moolenaar the Creator of Vim

mattnさんのBram Moolenaarについてのセッション。
1980年時点でvi cloneが沢山にあった。

Bram MoolenaarはAgideやa-a-p等他にも色々OSSを開発していた。
https://mattn.kaoriya.net/software/lang/zimbu/20100814005428.htm

Bram MoolenaarはGooglerだったことはあるが、基本的には職業不肖。
vimと非同期処理の話。
neovim誕生の流れ。
vimにterminalが実装された話。
mattnさんとbramの思い出話。
Bram「英語ができなくても良いじゃない。僕たちにはCという共通言語がある」

vim.org に参加した話。
** Revolutionizing Vim/Neovim Plugin Development ~ An In-Depth Look into Denops

ありすえさんのdenopsの発表。
DenopsのProsは速いし、開発しやすい。
Consは余計な依存が増える、プロセス起動のオーバーヘッドがある、rpc固有の問題がある、知名度が低い。
denopsを何故使うのか。
denopsのメカニズム、shared serverを使う。
denopsでplugin作成についての流れ。
https://zenn.dev/lambdalisue/articles/b4a31fba0b1ce95104c9
** Looking back at vim meetup
ゴリラ.vimを28回開催した話。
ゴリラ.vimはどんな感じか。
ゴリラ.vimを初めたきっかけ。
** Developing a Vim plugin with Ruby, or when in Ruby do as the Rubyists do

https://speakerdeck.com/okuramasafumi/developing-a-vim-plugin-with-ruby

Ruby ASTを利用する。
Rubyでも拡張が書ける。
LSPは巨大なjsonなので読むが大変。

** Modern techniques for implements insert mode plugins / Why use IME within text editor?

insert modeについて。
skkeltonの開発について。
vimのCmdの話。
modeの管理がglobal mode。
IMEの開発が難しい話。

** Boost your vimrc with some template techniques!

https://zenn.dev/aiya000/articles/76e60375898409

https://github.com/vim-jp/vital.vim

* LT
* 懇親会
Shougoさんに「org-modeをvimでも欲しくないんですか？」って聞いたら「あれは無理」

* 終わりに
