name: Run setup-nix
description: Set up Nix environment for GitHub Actions

inputs:
  cachix-auth-token:
    required: true
  cachix-signing-key:
    required: true

runs:
  using: composite
  steps:
    - name: hoge
      shell: bash
      run: |
        echo "Auth token is: '${{ inputs.cachix-auth-token }}'"
        echo "Signing key is: '${{ inputs.cachix-signing-key }}'"
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v14
      with:
        name: takeokunn-blog
        authToken: '${{ inputs.cachix-auth-token }}'
        signingKey: '${{ inputs.cachix-signing-key }}'
